### ISSUE TITLE
Types aren't being shipped

### ISSUE THREAD

**Issue by nbbaier** [devsgnr/breadroll#26]
It seems that you're not shipping `index.d.ts` with the library. This is probably because of `noEmit: true` in `tsconfig.json`. 

<img width="1012" alt="Screenshot 2024-07-24 at 10 53 33 PM" src="https://github.com/user-attachments/assets/20c7879b-6e65-4e2e-935d-c58eadf38bed">

<img width="802" alt="Screenshot 2024-07-24 at 10 54 17 PM" src="https://github.com/user-attachments/assets/b814d277-1d4d-4d27-95fe-30b68d377078">

**Comment by devsgnr** [comment]
Thank you @nbbaier for catching this - I'll be pushing a fix today.
